# Generated by Django 5.2.6 on 2025-09-12 09:29

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Категория')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Категорию услуг',
                'verbose_name_plural': '1.Категории услуг',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Nav',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=100, verbose_name='элемент навигации')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='URL')),
                ('image', models.ImageField(blank=True, upload_to='images', verbose_name='Изображение')),
                ('annotations1', models.TextField(blank=True, verbose_name='первое значение')),
                ('annotations2', models.TextField(blank=True, verbose_name='второе значение или ссылка на карту')),
            ],
            options={
                'verbose_name': 'контакты и навигацию',
                'verbose_name_plural': '5.НЕ трогать',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=100, verbose_name='Объявление')),
                ('content', models.TextField(blank=True, verbose_name='Текст объявления')),
                ('is_published', models.BooleanField(default=True, verbose_name='Публикация')),
            ],
            options={
                'verbose_name': 'Объявление',
                'verbose_name_plural': '6.Объявление',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Prices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='URL')),
                ('content', models.TextField(blank=True, verbose_name='Цены')),
                ('extraLink', models.CharField(blank=True, max_length=100, verbose_name='Ссылка на дополнительную информацию(если есть)')),
                ('is_published', models.BooleanField(default=True, verbose_name='Публикация')),
            ],
            options={
                'verbose_name': 'Цены',
                'verbose_name_plural': '3.Цены',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Extra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extra_image', models.ImageField(blank=True, upload_to='images', verbose_name='Изображение если есть')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='URL')),
                ('content', models.TextField(blank=True, verbose_name='Подробное описание')),
                ('is_published', models.BooleanField(default=True, verbose_name='Публикация')),
                ('extraContent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='smart.prices', verbose_name='Дополнительня информация о...')),
            ],
            options={
                'verbose_name': 'Дополнительную информацию',
                'verbose_name_plural': '4.Дополнительная информация',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='URL')),
                ('menu_image', models.ImageField(upload_to='images', verbose_name='Изображение в меню')),
                ('page_image', models.ImageField(upload_to='images', verbose_name='Изображение на странице')),
                ('annotation', models.TextField(blank=True, verbose_name='Рекламное описание ')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Время изменения')),
                ('is_published', models.BooleanField(default=True, verbose_name='Публикация')),
                ('gallery_link', models.CharField(blank=True, max_length=100, verbose_name='ссылка на фотографии')),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='smart.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Фотоуслуги и сувениры',
                'verbose_name_plural': '2.Фотоуслуги и сувениры',
                'ordering': ['time_create', 'title'],
            },
        ),
        migrations.AddField(
            model_name='prices',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='smart.services', verbose_name='Услуга'),
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='Заголовок')),
                ('gallery_image', models.ImageField(blank=True, upload_to='images', verbose_name='Фото')),
                ('content', ckeditor.fields.RichTextField(blank=True, verbose_name='Описание фотографии')),
                ('is_published', models.BooleanField(default=True, verbose_name='Публикация')),
                ('galleryLink', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='smart.services', verbose_name='Ссылка на услугу')),
            ],
            options={
                'verbose_name': 'фото в галерею',
                'verbose_name_plural': 'Галерея',
                'ordering': ['id'],
            },
        ),
    ]
